spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sport_play?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  mvc:
    log-request-details: true
server:
  port: 9090
mybatis-plus:
  type-aliases-package: spring.boot.sportplay.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

